cc_library(
    name = "primefield",
    visibility = ["//visibility:public"],
    hdrs = [
        "primefield/traits.hpp",
        "primefield/exception.hpp",
        "primefield/inverse.hpp",

    ],
    # The includes below makes it so that clients of this library
    # can skip the src/libs prefix when including header files
    # from this library (hdrs argument)
    includes = [""],
)


